import type { Metadata } from "next";
import { Inter,Poppins } from "next/font/google";
import "./globals.css";

const roboto = Poppins({
  weight: ['100','200','300','400','500','700'],
  style: ['normal', 'italic'],
  subsets: ['latin'],
  display: 'swap',
})
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`w-screen h-screen ${roboto.className}`}>
          {children}
      </body>
    </html>
  );
}
