# Generated by Django 4.2.6 on 2023-10-31 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_stock_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='closePrice',
            field=models.FloatField(default=0),
        ),
    ]
